name: Build and Publish Template CVs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    permissions:
      contents: write
    strategy:
      matrix:
        lang: ${{ fromJson(vars.LANGS) }}

    steps:
    - uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        apt-get update
        apt-get install -y gh
        git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Build the CV template
      run: |
        cd ${{ matrix.lang }}
        lualatex -interaction=nonstopmode cv.tex
        lualatex -interaction=nonstopmode cv-avatar.tex
        mv cv.pdf ${{ matrix.lang }}.pdf
        mv cv-avatar.pdf ${{ matrix.lang }}-avatar.pdf
        
    - name: Uplaod PDF to GitHub Release
      run: |
        gh release upload ${{ github.event.release.tag_name }} ${{ matrix.lang }}/${{ matrix.lang }}.pdf
        gh release upload ${{ github.event.release.tag_name }} ${{ matrix.lang }}/${{ matrix.lang }}-avatar.pdf
      env:
        GH_TOKEN: ${{ github.token }}
